; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
build_flags = 
	-D USBCON
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	;-D debug
	-D battery_in=PB1
	-D Module_power_2400=PB9
	-D joystick_Y=PA1
	-D joystick_T=PA0
	-D AUX2=PB5
	-D AUX1=PB0
	-D BTN_BACK=PB14
	-D BTN_NEXT=PA8
	-D BTN_PREV=PB15
	-D BTN_OK=PB13
	-D ELRS_Serial_2400=Serial1
	-D CRSF_baudrate=400000
	-D CRSF_TIM_DEF=TIM3
	;-D SCHOOL
monitor_dtr = 1
lib_extra_dirs = 
	$PROJECT_DIR/lib/uEEPROMlib-master
lib_deps = olikraus/U8g2@^2.36.16
monitor_speed = 115200

[env:stm32f411]
platform = ststm32
board = genericSTM32F411CE
framework = arduino
upload_protocol = stlink
build_flags = 
	-DUSBCON
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D battery_in=PB_1
	-D Module_power_2400=PA_5
	-D joystick_Y=PA_1
	-D joystick_T=PA_0
	-D AUX1=PB_5
	-D AUX2=PB_0
	-D BTN_BACK=PB_13
	-D BTN_NEXT=PB_15
	-D BTN_PREV=PA_8
	-D BTN_OK=PB_14
	-D ELRS_Serial_2400=Serial1
	-D CRSF_baudrate=800000
	-D CRSF_TIM_DEF=TIM3
monitor_dtr = 1
lib_extra_dirs = 
	$PROJECT_DIR/lib/uEEPROMlib-master
lib_deps = olikraus/U8g2@^2.36.16

[env:robotdyn_blackpill_f303cc]
platform = ststm32
board = robotdyn_blackpill_f303cc
framework = arduino
upload_protocol = dfu
build_flags = 
	-D USBCON
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D debug
	-D battery_in=PB1
	-D Module_power_2400=PB8
	-D joystick_Y=PA_0
	-D joystick_T=PA1
	-D AUX1=PB5
	-D AUX2=PB0
	-D BTN_BACK=PB13
	-D BTN_NEXT=PB15
	-D BTN_PREV=PA8
	-D BTN_OK=PB14
	-D ELRS_Serial_2400=Serial1
	-D CRSF_baudrate=400000
	-D CRSF_TIM_DEF=TIM2
	-D Trainer_pin=PB10
	-D SCHOOL
monitor_dtr = 1
lib_extra_dirs = 
	$PROJECT_DIR/lib/uEEPROMlib-master
	 
monitor_speed = 115200
lib_deps = olikraus/U8g2@^2.36.16
